name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./
    - name: Build
      run: dotnet build --no-restore -c release ./
    - name: Test
      run: dotnet test --no-build --verbosity normal -c release ./src/Apparatus.AOT.Reflection.Tests/
    - name: Publish AOT.Reflection NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: ./src/Apparatus.AOT.Reflection/Apparatus.AOT.Reflection.csproj
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
